version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sistema
    ports:
      - 3307:3306
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/install_db.sql"
    networks:
      - backend


  client-ui:
    depends_on:
      - api
    build:
      context: ./client
      args:
        - 80:80
    ports:
      - 80:3000
    environment:
      - REACT_APP_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./client:/client
      - /client/node_modules
    command: ["npm", "start"]
    networks:
      - frontend  

  api:
    depends_on:
      - mysqldb
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sistema
      - DB_PORT=3306
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "./wait-for-it.sh", "mysqldb:3306", "--", "npm", "run", "dev"]
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend

volumes: 
  db:

networks:
  backend:
  frontend: